max_epochs: 7
model_type: bert # bert or libert
formalisms: ud # source of linguistic information - ud spacy dm psd eud eud_pp bart
baseline: [false]

auxiliary_tasks: ["matched-AT"]   # options: "pattern", "matched-AT"
auxiliary_layers: [10,11,12]

data: rl lr  # ld dl ; rl rd lr ld dr dl ; device restaurants laptops 
limit_data: 1.0
splits: 1
seeds: [25] # [25, 26, 11] [42, 23, 17, 7]
tag: fast-bert-AT-aux-layers-10_11_12 # optional: name this experiment version
metric: asp_f1
num_workers: 44
gpus: [3]
parallel: true

li_layer: #5
li_layers: #[2]
all_layers: true
relation: ""
parse_probs: false
replace_final: false
duplicated_rels: false
transpose: false
use_syntactic_rels: false

do_train: true
do_predict: true

overwrite_cache: true # if false, loads features from cached file (faster)
cache_dir: # default: nlp-architect/nlp_architect/cache
output_dir: # default: nlp-architect/nlp_architect/cache/li-bert-models
labels: labels.txt # relative to nlp_architect/models/li_bert/data

model_name_or_path: bert-base-uncased
train_batch_size: 8
eval_batch_size: 8
max_seq_length: 64
adam_epsilon: 1.0e-08
fast_dev_run: false
accumulate_grad_batches: 1
learning_rate: 5.0e-05
gradient_clip_val: 1.0
n_tpu_cores: 0
resume_from_checkpoint: null
tokenizer_name: null
val_check_interval: 1.0
warmup_steps: 0
weight_decay: 0.0
logger: true